### ISSUE TITLE
Reduce dependencies during install and distribute compiled version of the library

### ISSUE THREAD

**Issue by kmalakoff** [nihey/react-clipboard#1]
Thanks for putting this together. It is working for my use case.

It is slow to install. Would you be able to distribute a pre-compiled version of your library and remove all of the dependencies in your package.json dependency sections except for Clipboard.js and React?

Here's an example of how to compile and release a universal module: https://github.com/NuCivic/react-nvd3

Thanks!

**Comment by nihey** [comment]
Sure! I was thinking about doing it (with `webpack`) after I'm done with all the issues on the component itself (and possibly adding to a CDN like [cdnjs](https://cdnjs.com/)).

I'm a little out of time this week, but I'm sure I'll be able to visit all these issues by the end of the weekend.

If you want to contribute to this project you're welcome as well - just let me know if you're doing something so we don't run into the same issues.

**Comment by nihey** [comment]
> (...) remove all of the dependencies in your package.json dependency sections except for Clipboard.js and React?

I was thinking about removing React too, leaving only Clipboard.js to be packed in the compiled bundle.

It is expected that a application that includes `react-clipboard.js` must also have React - so adding React again may cause some errors. It also leaves me out of the problem of having to specify which version of React the dependant must use (`0.13.x` or `0.14.x`) - as we are transitioning into `0.14.x`.

**Comment by kmalakoff** [comment]
I wouldn't put anything in the compiled bundle except your library. By using webpack's UMD feature, it will handle importing React and Clipboard on window global, CommonJS, or AMD.

The reason I left them in dependencies was if someone only installs react-clipboard.js, they will also be installed. With npm 3 flattening the hierarchy and getting rid of peer dependencies, this will probably be best - it won't install them twice.

**Comment by nihey** [comment]
> I wouldn't put anything in the compiled bundle except your library.

I saw it on the on the PR, that's definitely the way to go.

> With npm 3 flattening the hierarchy and getting rid of peer dependencies, this will probably be best - it won't install them twice.

Yes, at least the installation time will be greatly reduced (considering that React will probably already be on the dependency tree).

I think I'll just try to update React on `package.json` to `0.14.x` and see what happens when I include it on a project using `0.13.x` - just to get rid of the `out of date` badge on `README.md`.  Probably when I have a little more free time (so that I don't create any more problems by rushing the development).

Thanks for the help and feedback.
