### ISSUE TITLE
call destroy to cleanup

### ISSUE THREAD

**Issue by timaschew** [nihey/react-clipboard#11]
found out that `destroy` is never called, so the event listener will never be cleaned up when unmounting the react component. This should be handled in `componentWillUnmount`

from clipboard.js docs:
> var clipboard = new Clipboard('.btn');
clipboard.destroy();

**Comment by nihey** [comment]
You're right, I'll be fixing it shortly

**Comment by nihey** [comment]
It should be fixed by now. I'll be packaging it into a new release soon.

**Comment by nihey** [comment]
I should be released on [`0.1.5`](https://github.com/nihey/react-clipboard/releases/tag/0.1.5), thanks again for the input.
