### ISSUE TITLE
Cannot run mocha tests

### ISSUE THREAD

**Issue by olivierpichon** [nihey/react-clipboard#16]
Hi,

Thanks a lot for your work on `react-clipboard`!

We have an issue when running mocha tests using:
`mocha --compilers js:babel-core/register ...`

We have the following error:

```
(function (exports, require, module, __filename, __dirname) { import React fro
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
```

This is because the main index file of the package is using ES6 syntax. Babel, by default does not try to do any transformations for node_modules packages:

http://babeljs.io/docs/usage/require/#usage

We tried to do what was suggested here, although it is really advised that node modules, for accessibility purposes, use a transpiled version:

http://stackoverflow.com/questions/31822593/import-a-module-from-node-modules-with-babel-but-failed#answer-31822668

To make it work with Babel, we also had to do require a custom file as described here:

http://stackoverflow.com/questions/20049790/how-to-pass-compiler-options-to-mocha#answer-28700064

We got passed this issue but got another one here:

```
/Users/olivier/Documents/sources/outfit_repos/outfit/node_modules/clipboard/node_modules/good-listener/node_modules/delegate/node_modules/closest/node_modules/matches-selector/index.js:6
var proto = Element.prototype;
            ^
ReferenceError: Element is not defined
    at Object.<anonymous> (/Users/olivier/Documents/sources/outfit_repos/outfit/node_modules/clipboard/node_modules/good-listener/node_modules/delegate/node_modules/closest/node_modules/matches-selector/index.js:6:13)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
```

Are we missing anything?

Thanks a lot for your feedback!

**Comment by nihey** [comment]
Hello!

> Thanks a lot for your work on `react-clipboard`!

You're Welcome :)

> This is because the main index file of the package is using ES6 syntax. Babel, by default does not 
> try to do any transformations for node_modules packages:

Oh, just missed that, [this should be the entry point](https://github.com/nihey/react-clipboard/blob/master/dist/react-clipboard.js) on the [package.json](https://github.com/nihey/react-clipboard/blob/master/package.json#L5), thanks for reporting.

> Are we missing anything?

It seems this error is happening on one my dependency's dependency, [matches-selector](https://github.com/ForbesLindesay/matches-selector/blob/master/index.js) (the chain of dependencies is: [react-clipboard.js](https://github.com/nihey/react-clipboard) -> [clipboard](https://github.com/zenorocha/clipboard.js) -> ... -> [matches-selector](https://github.com/ForbesLindesay/matches-selector/blob/master/index.js)).

`matches-selector` assumes you're running on a Browser environment, having Browser environment globals (`window`, `document`, ...). Being specific, it assumes that you have `Element` global.

Mocha on the other way, runs in Node environment, thus, not providing you the globals `matches-selector` is using.

A possible alternative is to run your test on a `headless browser`, such as [PhantomJS](http://phantomjs.org/). But if you have good reasons to still be using `mocha` (e.g.: most of your test routines are there and migrating it would be time consuming) there should be a way to spawn a subprocess with [Node's API](https://nodejs.org/api/child_process.html).

My recommended test suite to Web Applications is currently [`jest`](https://facebook.github.io/jest/), it is very React-friendly, and runs on top of `PhantomJS`, that means all your browser globals will be there for you.

Thanks for the detailed info on your problem, I hope my answer helps you!

**Comment by olivierpichon** [comment]
It really helped indeed @nihey!

Thanks a lot for your time and for your great work.
