### ISSUE TITLE
onError doesn't working

### ISSUE THREAD

**Issue by danielnass** [nihey/react-clipboard#17]
I'm trying to use onError function, but doesn't work.

The onSuccess works like a charm :)

Can you help with this?

**Comment by nihey** [comment]
> The onSuccess works like a charm :)

Sweet :)

> I'm trying to use onError function, but doesn't work.

I haven't been able to reproduce this behavior. Could you provide some more info on this? (which browser you used, any logs, a code snippet).

> Can you help with this?

The following snippet worked on Firefox 40 (not supported by `clipboard.js`, thus, triggering an error)
```javascript
var MyView = React.createClass({                                               
  onError: function() {                                                        
    console.log('XXX');                                                        
  },                                                                           
                                                                                  
  render: function() {                                                            
    return <div>                                                                  
      <Clipboard data-clipboard-text="I'll be copied" onError={this.onError}>  
        copy to clipboard                                                         
      </Clipboard>                                                             
    </div>;                                                                    
  },                                                                           
});                                                                               
                                                                                  
ReactDOM.render(<MyView/>, document.getElementById('react-body')); 
```

`react-clipboard.js` only uses [`clipboard.js`](https://github.com/zenorocha/clipboard.js) under the hood, binding `prop` patterns to their API. One common mistake that could cause such behavior to occur would be typos.

Considering the code above, typos such as these would cause `onError` to never be triggered.
```javascript
// Won't work, causes "TypeError: evtArr[i].fn is undefined" when triggered
<Clipboard data-clipboard-text="I'll be copied" onError={this.onErro}>
```
```javascript
// Won't work, fails silently, without any error logs
<Clipboard data-clipboard-text="I'll be copied" onErro={this.onError}>
```

**Comment by danielnass** [comment]
Thanks for reply me @nihey, and sorry for this, the error was on my code, onError works well like onSuccess :tada:

I'll still watching react-clipboard for future releases :)
Best regards!
