### ISSUE TITLE
propagate attributes to <button>

### ISSUE THREAD

**Issue by zdila** [nihey/react-clipboard#19]
Please propagate all non-ClipboardButton specific attributes to contained button. Currently I can't set eg. `title`. or `id` (which is now autogenerated). Thanks.

**Comment by nihey** [comment]
`title` or `id` may be propagated by using `button-title` or `button-id`:

Any `button-*` should be propagated as the sole content, without `button-`. `button-title` -> `title`
```
<ClipboardButton data-clipboard-text="I'll be copied" button-title="I'm a tooltip">
        copy to clipboard
</ClipboardButton>
```
