### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': '#7k62hl3obn0qw7b9' is not a valid selector.

### ISSUE THREAD

**Issue by kmalakoff** [nihey/react-clipboard#2]
It looks like the way you are generating ids sometimes runs into problems. 

Why not just use a counter and something much simpler like `__react_clipboard_${counter}` ?

**Comment by nihey** [comment]
You're right, that's actually a much better solution, we could add a static counter on the `ClipboardButton` component to do this.
