### ISSUE TITLE
Failed propType: Required prop `value` was not specified

### ISSUE THREAD

**Issue by DDChiang** [nihey/react-clipboard#20]
I followed the documentation down to the "t" but for some reason, I'm getting this error upon basic rendering: "Warning: Failed propType: Required prop `value` was not specified in `<<anonymous>>`."

Here's my code:

    var React = require('react');
    var ClipboardButton = require('react-clipboard');

    var TestComponent = React.createClass({
      render: function() {
       return (
          <div>
           <ClipboardButton data-clipboard-text="test copy text">
                  Child Text
            </ClipboardButton>
        </div>
        );
      }
    });

    module.exports = TestComponent;
`

I was really hoping to integrate this module into my project. Any help would be much appreciated!

**Comment by nihey** [comment]
It seems you've got the wrong `react-clipboard` library, try downloading `react-clipboard.js` -> `npm i react-clipboard.js`.

`react-clipboard` is a library by @WickyNilliams, and it requires a `prop` named `value` (you can check it [here](https://github.com/WickyNilliams/react-clipboard/blob/master/index.js#L10))

Glad you're using it, I hope I could be of any help!

**Comment by WickyNilliams** [comment]
Yup, that will definitely cause errors with my component :) 

Shame the names are so similar on npm. It might be a source of more confusion in future. I wonder if naming this repo the same as the npm package would mitigate this? Your call, of course

**Comment by nihey** [comment]
> I wonder if naming this repo the same as the npm package would mitigate this?
Definitely, I shall do it on the near future. When I created the repo I was hoping to name the `npm` package as `react-clipboard` too, but found out it was already taken.

**Comment by nihey** [comment]
`react-clipboard` url changed to `react-clipboard.js` in https://github.com/nihey/react-clipboard.js/commit/9f5ca71bcfba94b3910230aa1c1ab5cc66221f5c
