### ISSUE TITLE
Install broken

### ISSUE THREAD

**Issue by kmalakoff** [nihey/react-clipboard#6]
```
npm ERR! react-clipboard.js@0.0.2 install: `webpack -p`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-clipboard.js@0.0.2 install script 'webpack -p'.
npm ERR! This is most likely a problem with the react-clipboard.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-clipboard.js
npm ERR! There is likely additional logging output above.
```

I don't think it is a good idea to be compiling assets on release. Users of the library should get a known-to-be tested version of the library instead of something that is dynamically generated.

**Comment by nihey** [comment]
> I don't think it is a good idea to be compiling assets on release.

You're right, I actually turned out to be a really bad idea.

I've done a temporary fix for this issue and released it on `npm`, so that `npm install react-clipboard.js` should not be broken right now.

A permanent fix for this issue, along with #1 will be released on this weekend.
