### ISSUE TITLE
provide type property for the button

### ISSUE THREAD

**Issue by timaschew** [nihey/react-clipboard#9]
If I use the element which is created by the library within a form and press the copy button it triggeres a submit of my form, which is not the expected behavior.

Fix would be if the `type` can be set from the caller, like

```
<ClipboardButton type={'button'} option-text={this.getText} onSuccess={this.onSuccess}>
   copy to clipboard
</ClipboardButton>
```

**Comment by nihey** [comment]
Nice catch, I'll be updating it shortly

**Comment by nihey** [comment]
It should be fixed by now. @timaschew Thanks for the input, let me know if you need anything else.

**Comment by timaschew** [comment]
wow, this was fast, thanks you :+1:

**Comment by timaschew** [comment]
found another property, which seems to be important: `title` to provide tooltips for the button.

I'm not sure if there are some other properties which will be realized later, so maybe it can be passed more dynamically somehow?

**Comment by nihey** [comment]
> I'm not sure if there are some other properties which will be realized later, so maybe it can be passed more dynamically somehow?

Probably, there will be others. I think I'll add a property set following the `button-*` pattern. This way, `button-title="foobar"` will achieve the `<button title="foobar"></button>` result. This way, I think it'll be generic enough for anything to be done.

PS: I'll keep the `type` prop option as well for backwards compatibility.

**Comment by nihey** [comment]
https://github.com/nihey/react-clipboard/commit/56aafd8c5b31722ca4f6e7443e28c2b58e9c320a Should allow any button attribute adding. Documentation related to this issues has been appended to https://github.com/nihey/react-clipboard#usage .

Thanks for the feedback again, if there is anything else, just let me know :+1:
